### ISSUE TITLE
회원 가입시 추가 설정 기능 구현(프로필 이미지 업로드)

### ISSUE THREAD

**Issue by chanbyoung** [chanbyoung/OAuth2JwtLogin#12]
## 📝 Description
회원 가입 시 추가 설정을 구현합니다
프로필 사진과 닉네임을 설정할 수 있습니다.

## ☑️ TODO
- [x] 이미지 엔티티 추가 및 연관관계 설정 
- [x] 추가 설정 DTO 작성
- [x] 회원 가입 시 추가 설정 기능 구현
- [x] 회원 프로필 조회로 사진 및 닉네임 저장 확인
- [x] 토큰 발급 방식 변경
